### Test homepage
GET http://localhost:3000/

### Test sending notification to a connected subscriber
POST http://localhost:3000/push-notification
Content-Type: application/json

{
  "phone": "1234567890",
  "data": "Dear Edie TESTING COMPANY BRANCH END OF DAY REPORT on 23/09/2024:No.OfActiveLoans: 675;No.OfCustomersPaid: 317;CollectionRate: 47%;NewCustomers: 3;TotalCollections: 7,579,400;No.OfRenewedPaid: 19;TotalAmntRenewedPaid: 342,000;No.OfLoansDisbursed: 23;TotalAmntDisbursed: 6,550,000;No.OfLoansRenewed: 7;TotalAmntRenewed: 1,967,500;PrincipalBalance: 130,713,014;InterestBalance: 21,684,657;TotalLoanPortfolio: 152,397,671;No.OfSavingAdded: 11;No.OfSavingRemoved: 9;OpeningCash: 825,800;PrincipalCollected: 6,368,355;InterestCollected: 1,211,045;ProcessingFees: 335,000;LedgerFees: 30,000;UnrealisedInterestIncome: 207,628;SavingsAndDeposits: 129,200;BankDeposits: 1,189,000;TotalExpenses: 135,000;LoanDisbursements: 6,550,000;SavingsWithdraws: 216,200;ClosingCash: 809,200;"
}

### Test sending notification to a connected subscriber
POST  https://pinkapple-reports-834b63200c6b.herokuapp.com/push-notification
Content-Type: application/json

{
  "phone": "1234567890",
  "data": "Dear Edie TESTING COMPANY BRANCH END OF DAY REPORT on 23/09/2024:No.OfActiveLoans: 675;No.OfCustomersPaid: 317;CollectionRate: 47%;NewCustomers: 3;TotalCollections: 7,579,400;No.OfRenewedPaid: 19;TotalAmntRenewedPaid: 342,000;No.OfLoansDisbursed: 23;TotalAmntDisbursed: 6,550,000;No.OfLoansRenewed: 7;TotalAmntRenewed: 1,967,500;PrincipalBalance: 130,713,014;InterestBalance: 21,684,657;TotalLoanPortfolio: 152,397,671;No.OfSavingAdded: 11;No.OfSavingRemoved: 9;OpeningCash: 825,800;PrincipalCollected: 6,368,355;InterestCollected: 1,211,045;ProcessingFees: 335,000;LedgerFees: 30,000;UnrealisedInterestIncome: 207,628;SavingsAndDeposits: 129,200;BankDeposits: 1,189,000;TotalExpenses: 135,000;LoanDisbursements: 6,550,000;SavingsWithdraws: 216,200;ClosingCash: 809,200;"
}


### Test sending notification to a disconnected subscriber (message will be queued)
POST http://localhost:3000/push-notification
Content-Type: application/json

{
  "phone": "0987654321",
  "data": "Please review your latest updates."
}

### Save or Update Transaction (by company_name & branch_name)
POST http://localhost:3000/save-savings-transactions_dev
Content-Type: application/json

{
  "TrnDate": "2024-10-19",
  "AccountNumber": "05502002910",
  "AccountName": "YENOSU WASSWA",
  "SavingsMonth": "OCTOBER",
  "SavingsYear": "2024",
  "SavingsAdded": "8990000.0",
  "SavingsRemoved": "0.00",
  "SavingsRunningBalance": "8900000.0",
  "OtherOne": "Regular Savings for YENOSU WASSWA's Savings on 19/10/2024",
  "OtherTwo": "NA",
  "OtherThree": "NA",
  "OtherFour": "NA",
  "OtherFive": "NA",
  "company_name": "My Company1",
  "branch_name": "Main BranchY",
  "user_id": 101
}



### Save Transaction
POST http://localhost:3060/save-savings-transactions
Content-Type: application/json

{
     "TrnId": "1",
     "TrnDate": "2024-10-19",
     "AccountNumber": "05502002410",
     "AccountName": "YENOSU WASSWA",
     "SavingsMonth": "OCTOBER",
     "SavingsYear": "2024",
     "SavingsAdded": "800000.0",
     "SavingsRemoved": "-",
     "SavingsRunningBalance": "800000.0",
     "OtherOne": "Regular Savings for YENOSU WASSWA's Savings Processed on 19/10/2024",
     "OtherTwo": "NA",
     "OtherThree": "NA",
     "OtherFour": "NA",
     "OtherFive": "NA"
}


### Get Transaction by TrnId
GET http://localhost:3000/get-transaction?TrnId=YOUR_TRN_ID_HERE
Content-Type: application/json




### Get Transaction by TrnId
GET http://localhost:3060/get-all-savings-transaction
Content-Type: application/json



### Get Transaction by TrnId
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/get-all-savings-transaction
Content-Type: application/json







### Get Paginated Transaction Data with Search
GET http://localhost:3060/get-all-savings-transaction-search?term=Natamba&page=1&pageSize=1000
Content-Type: application/json


### Get Paginated Transaction Data with Search
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/get-all-savings-transaction-search?term=Natamba&page=1&pageSize=1000
Content-Type: application/json

### Search Savings Transaction
GET http://localhost:3060/search-savings-transaction?term=Naha
Content-Type: application/json


### Get Transaction by TrnId
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/search-savings-transaction?term=Naha
Content-Type: application/json



### Create Saving Transaction
POST http://localhost:3060/create-saving
Content-Type: application/json

{
  "TrnId": "8617",
  "amountSaved": 200000
}

###
GET https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/get-all-savings-transaction_dev?company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch


###
GET http://localhost:3000/get-all-savings-transaction_dev?company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch

###
GET https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/get-all-savings-transaction-search_dev?term=john &page=1&pageSize=10&company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch


###
GET https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/search-savings-transaction_dev?term=NAMU&company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch
Content-Type: application/json




###
POST http://localhost:3000/create-saving_dev
Content-Type: application/json

{
  "TrnId": "31154",
  "amountSaved": 20000,
  "company_name": "SHILOH FINANCES LTD",
  "branch_name": "Bwaise Branch",
  "user_id": 10003
}


### Create Saving Dev
POST https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/create-saving_dev
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2NhbF91c2VyX2lkIjoxMDAwNywidGl0bGUiOiJEaXJlY3RvciIsInJvbGUiOiJJbnRlcm5lZSIsImNvbXBhbnlfbmFtZSI6IlNISUxPSCBGSU5BTkNFUyBMVEQiLCJicmFuY2hfbmFtZSI6IkJ3YWlzZSBCcmFuY2giLCJpYXQiOjE3NDQ3NDM3NjQsImV4cCI6MTc0NDc3MjU2NH0.3IiBdCeMSmlhBjLr3dKdfx6E6nLjuQozoN8qpEmyjDY
Content-Type: application/json

{
  "TrnId": 31149,
  "amountSaved": 20000
}





### Get unreconciled savings
GET http://localhost:3060/savings/unreconciled
Content-Type: application/json


###
GET https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/savings/unreconciled_dev?company_name=EDU%20TRINITY%20INVESTMENT%20LIMITED&branch_name=Masanafu%20Branch



### Get unreconciled savings
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/savings/unreconciled
Content-Type: application/json


### Get all savings records
GET http://localhost:3060/savings/all
Content-Type: application/json


### Get all savings records
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/savings/all
Content-Type: application/json


### Reconcile savings records
POST http://localhost:3060/savings/reconcile
Content-Type: application/json

{
  "id": [12, 14,16] 

}


### Reconcile savings records
POST https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/savings/reconcile_dev
Content-Type: application/json

{
  "id": [4668, 4669] 

}

### Reconcile savings records
POST https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/savings/reconcile
Content-Type: application/json


{
  "id": [12, 14,16] 

}


### Get all loan transactions
GET http://localhost:3060/get-all-loan-transactions
Content-Type: application/json


### Get all loan transactions
GET https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/get-all-loan-transactions_dev?company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch
Content-Type: application/json


### Get all loan transactions
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/get-all-loan-transactions
Content-Type: application/json



### Get loan transactions with search and pagination
GET http://localhost:3060/get-all-loan-transactions-search?term=Puddy&page=1&pageSize=10
Content-Type: application/json

###
GET http://localhost:3000/get-all-loan-transactions-search_dev?term=''&page=1&pageSize=10&company_name=?company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch

### Get loan transactions with search and pagination
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/get-all-loan-transactions-search?term=Puddy&page=1&pageSize=10
Content-Type: application/json


### Search loan transactions
GET http://localhost:3060/search-loan-transaction?term=Junda
Content-Type: application/json

###
GET http://localhost:3000/search-loan-transaction_dev?term=john&company_name=SHILOH%20FINANCES%20LTD&branch_name=Bwaise%20Branch


### Search loan transactions
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/search-loan-transaction?term=Junda
Content-Type: application/json


### Create loan payment
POST http://localhost:3060/create-loan-payment
Content-Type: application/json

{
  "loan_id": "newloan05502015910",  
  "amountPaid": 10000000.00  
}


### Create Loan Payment Dev
POST http://localhost:3000/create-loan-payment_dev
Content-Type: application/json

{
  "id":"11603",
  "amountPaid": 10000,
  "company_name": "SHILOH FINANCES LTD",
  "branch_name": "Bwaise Branch",
  "user_id": 10001
}



### Example: create loan payment with JWT
POST  https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/create-loan-payment_dev
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJsb2NhbF91c2VyX2lkIjoxMDAwNywidGl0bGUiOiJEaXJlY3RvciIsInJvbGUiOiJJbnRlcm5lZSIsImNvbXBhbnlfbmFtZSI6IlNISUxPSCBGSU5BTkNFUyBMVEQiLCJicmFuY2hfbmFtZSI6IkJ3YWlzZSBCcmFuY2giLCJpYXQiOjE3NDQ3NDM3NjQsImV4cCI6MTc0NDc3MjU2NH0.3IiBdCeMSmlhBjLr3dKdfx6E6nLjuQozoN8qpEmyjDY
Content-Type: application/json

{
  "id": "11603",
  "amountPaid": 5000
}


### Create loan payment
POST https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/create-loan-payment
Content-Type: application/json

{
  "loan_id": "newloan05502015910",  
  "amountPaid": 10000000.00  
}


### Get unreconciled loan payments
GET http://localhost:3060/loans/unreconciled
Content-Type: application/json

### Get unreconciled loan payments
GET http://localhost:3000/loans/unreconciled_dev?company_name=EDU%20TRINITY%20INVESTMENT%20LIMITED&branch_name=Masanafu%20Branch
Content-Type: application/json


### Get unreconciled loan payments
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/loans/unreconciled
Content-Type: application/json



### Get all loan payments
GET http://localhost:3000/loans/all
Content-Type: application/json


### Get all loan payments
GET https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/loans/all
Content-Type: application/json


### Reconcile loan payments
POST http://localhost:3060/loans/reconcile
Content-Type: application/json

{
  "id": [1894]  
}


### Reconcile loan payments
POST http://localhost:3000/loans/reconcile_dev
Content-Type: application/json

{
  "id": [1894]  
}



### Reconcile loan payments
POST https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com/loans/reconcile
Content-Type: application/json

{
  "id": [1, 2, 3]  
}



### Login Request
POST http://localhost:3060/login
Content-Type: application/json

{
  "user_id": "10000",  
  "p_word_login": "aa" 
}



### Login Request
POST https://pinkapple-reports-printing-8964e6404c0e.herokuapp.com:3000/login
Content-Type: application/json

{
  "user_id": "10000",  
  "p_word_login": "aa" 
}


### Login to /login_dev
POST https://pinkapple-terminal-printing-de-e986dcfa78e5.herokuapp.com/login_dev
Content-Type: application/json

{
  "local_user_id": 10007,
  "password": "aa",
  "unique_user_code": "23077870"
}



###
POST http://localhost:3000/save-login-dev
Content-Type: application/json

{
  "username": "TestUser",
  "password_hash": "aaa",
  "company_name": "TestCo",
  "branch_name": "TestBranch",
  "local_user_id": 12345
  // Note: do NOT pass unique_user_code at all
}
